spring.application.name=hce-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-tiny-tooth-apgfvvym-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
ml.api.url=https://ml-api-inasistencias.onrender.com/predict

fabric.enabled=${FABRIC_ENABLED:false}
fabric.channel=${FABRIC_CHANNEL:hce-channel}
fabric.chaincode=${FABRIC_CHAINCODE:hce-traceability}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
